"""Data models for NegMAS App."""

from .mechanism import (
    MechanismType,
    MechanismTypeInfo,
    MECHANISM_TYPES,
    DeadlineParams,
    BaseMechanismParams,
    MechanismParams,  # Backwards compat alias
    SAOParams,
    TAUParams,
    GBParams,
    DisplayParams,
    MechanismConfig,
    default_config,
)
from .negotiator import (
    NegotiatorSource,
    BUILTIN_SOURCES,
    NegotiatorConfig,
    NegotiatorInfo,
    BOAComponentInfo,
    BOANegotiatorConfig,
)
from .scenario import ScenarioInfo, IssueInfo, ScenarioStatsInfo
from .session import (
    NegotiationSession,
    SessionStatus,
    OfferEvent,
    SessionNegotiatorInfo,
    SessionInitEvent,
    NEGOTIATOR_COLORS,
    COLORBLIND_COLORS,
    COLORBLIND_LINE_DASHES,
    COLORBLIND_MARKERS,
    AnalysisPoint,
    OutcomeSpaceData,
    PanelConfig,
    LayoutConfig,
    BUILTIN_LAYOUTS,
    default_layout,
    timeline_focused_layout,
)
from .settings import (
    AppSettings,
    GeneralSettings,
    NegotiationSettings,
    GeniusBridgeSettings,
    NegotiatorSourcesSettings,
    CustomNegotiatorSource,
    PathSettings,
    # Presets
    NegotiatorPreset,
    ScenarioPreset,
    NegotiatorsPreset,
    ParametersPreset,
    DisplayPreset,
    FullSessionPreset,
)
from .tournament import (
    TournamentStatus,
    TournamentConfig,
    CompetitorScore,
    NegotiationResult,
    TournamentProgress,
    TournamentResults,
    TournamentSession,
    FinalScoreMetric,
    FinalScoreStatistic,
)

__all__ = [
    # Mechanism
    "MechanismType",
    "MechanismTypeInfo",
    "MECHANISM_TYPES",
    "DeadlineParams",
    "BaseMechanismParams",
    "MechanismParams",
    "SAOParams",
    "TAUParams",
    "GBParams",
    "DisplayParams",
    "MechanismConfig",
    "default_config",
    # Negotiator
    "NegotiatorSource",
    "BUILTIN_SOURCES",
    "NegotiatorConfig",
    "NegotiatorInfo",
    "BOAComponentInfo",
    "BOANegotiatorConfig",
    # Scenario
    "ScenarioInfo",
    "IssueInfo",
    "ScenarioStatsInfo",
    # Session
    "NegotiationSession",
    "SessionStatus",
    "OfferEvent",
    "SessionNegotiatorInfo",
    "SessionInitEvent",
    "NEGOTIATOR_COLORS",
    "COLORBLIND_COLORS",
    "COLORBLIND_LINE_DASHES",
    "COLORBLIND_MARKERS",
    "AnalysisPoint",
    "OutcomeSpaceData",
    "PanelConfig",
    "LayoutConfig",
    "BUILTIN_LAYOUTS",
    "default_layout",
    "timeline_focused_layout",
    # Settings
    "AppSettings",
    "GeneralSettings",
    "NegotiationSettings",
    "GeniusBridgeSettings",
    "NegotiatorSourcesSettings",
    "CustomNegotiatorSource",
    "PathSettings",
    # Presets
    "NegotiatorPreset",
    "ScenarioPreset",
    "NegotiatorsPreset",
    "ParametersPreset",
    "DisplayPreset",
    "FullSessionPreset",
    # Tournament
    "TournamentStatus",
    "TournamentConfig",
    "CompetitorScore",
    "NegotiationResult",
    "TournamentProgress",
    "TournamentResults",
    "TournamentSession",
    "FinalScoreMetric",
    "FinalScoreStatistic",
]
